name: Workflow
on:
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: saying hello
        run: |
         echo "Hello world"
         echo github.event_name
         ENV