name: Workflow
on:
  push:
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }} 
    outputs: 
      flag: ${{ steps.set-flag.outputs.flag }}
    steps:
      - name: saying hello
        id: set-flag
        run: |
         echo "Hello world"
         echo ${{ github.event_name }}
         env
         sleep 30
        #  echo "::set-output name=flag::true"
  second_job:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }} && always()
    needs: [say_hello]
    steps:
      - name: second job
        if: ${{ needs.say_hello.outputs.flag }} 
        run: |
          echo "i second job"
